name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux builds
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
          
          # Windows builds
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - goos: windows
            goarch: arm64
            suffix: windows-arm64.exe
          
          # macOS builds
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o schemalyzer-${{ matrix.suffix }} cmd/schemalyzer/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: schemalyzer-${{ matrix.suffix }}
          path: schemalyzer-${{ matrix.suffix }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create checksums
        run: |
          cd artifacts
          for dir in */; do
            cd "$dir"
            sha256sum * > ../$(basename "$dir").sha256
            cd ..
          done
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*/*
            artifacts/*.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Schemalyzer ${{ github.ref_name }}
            
            Database schema comparison tool for PostgreSQL, MySQL, and Oracle.
            
            ### Installation
            
            Download the appropriate binary for your platform and add it to your PATH.
            
            ### Checksums
            
            SHA-256 checksums are provided for each binary.